/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'Article': RouteRecordInfo<'Article', '/article', Record<never, never>, Record<never, never>>,
    '/article/components/ArticleList': RouteRecordInfo<'/article/components/ArticleList', '/article/components/ArticleList', Record<never, never>, Record<never, never>>,
    '/article/components/CategoryList': RouteRecordInfo<'/article/components/CategoryList', '/article/components/CategoryList', Record<never, never>, Record<never, never>>,
    '/article/components/TagList': RouteRecordInfo<'/article/components/TagList', '/article/components/TagList', Record<never, never>, Record<never, never>>,
    'Dashboard': RouteRecordInfo<'Dashboard', '/', Record<never, never>, Record<never, never>>,
    '/dashboard/components/Ranking': RouteRecordInfo<'/dashboard/components/Ranking', '/dashboard/components/Ranking', Record<never, never>, Record<never, never>>,
    '/dashboard/components/Statistics': RouteRecordInfo<'/dashboard/components/Statistics', '/dashboard/components/Statistics', Record<never, never>, Record<never, never>>,
    '/dashboard/components/VisitorMap': RouteRecordInfo<'/dashboard/components/VisitorMap', '/dashboard/components/VisitorMap', Record<never, never>, Record<never, never>>,
    'Login': RouteRecordInfo<'Login', '/login', Record<never, never>, Record<never, never>>,
    'Moment': RouteRecordInfo<'Moment', '/moment', Record<never, never>, Record<never, never>>,
    'Profile': RouteRecordInfo<'Profile', '/profile', Record<never, never>, Record<never, never>>,
  }
}
