/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'Article': RouteRecordInfo<'Article', '/article', Record<never, never>, Record<never, never>>,
    'ArticleEdit': RouteRecordInfo<'ArticleEdit', '/article/edit', Record<never, never>, Record<never, never>>,
    'Authorize': RouteRecordInfo<'Authorize', '/authorize', Record<never, never>, Record<never, never>>,
    'Comment': RouteRecordInfo<'Comment', '/comment', Record<never, never>, Record<never, never>>,
    'Config': RouteRecordInfo<'Config', '/config', Record<never, never>, Record<never, never>>,
    'Dashboard': RouteRecordInfo<'Dashboard', '/', Record<never, never>, Record<never, never>>,
    'FriendlyLink': RouteRecordInfo<'FriendlyLink', '/friendly-link', Record<never, never>, Record<never, never>>,
    'Logging': RouteRecordInfo<'Logging', '/logging', Record<never, never>, Record<never, never>>,
    'Login': RouteRecordInfo<'Login', '/login', Record<never, never>, Record<never, never>>,
    'Moment': RouteRecordInfo<'Moment', '/moment', Record<never, never>, Record<never, never>>,
    'MomentEdit': RouteRecordInfo<'MomentEdit', '/moment/edit', Record<never, never>, Record<never, never>>,
    'NoteEdit': RouteRecordInfo<'NoteEdit', '/note/edit', Record<never, never>, Record<never, never>>,
    'NotePreview': RouteRecordInfo<'NotePreview', '/note/preview', Record<never, never>, Record<never, never>>,
    'OpenSource': RouteRecordInfo<'OpenSource', '/open-source', Record<never, never>, Record<never, never>>,
    'Profile': RouteRecordInfo<'Profile', '/profile', Record<never, never>, Record<never, never>>,
    'ProfileEdit': RouteRecordInfo<'ProfileEdit', '/profile/edit', Record<never, never>, Record<never, never>>,
    'Setting': RouteRecordInfo<'Setting', '/setting', Record<never, never>, Record<never, never>>,
    'User': RouteRecordInfo<'User', '/user', Record<never, never>, Record<never, never>>,
  }
}
