/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'Article': RouteRecordInfo<'Article', '/article', Record<never, never>, Record<never, never>>,
    '/article/components/ArticleList': RouteRecordInfo<'/article/components/ArticleList', '/article/components/ArticleList', Record<never, never>, Record<never, never>>,
    '/article/components/CategoryList': RouteRecordInfo<'/article/components/CategoryList', '/article/components/CategoryList', Record<never, never>, Record<never, never>>,
    '/article/components/TagList': RouteRecordInfo<'/article/components/TagList', '/article/components/TagList', Record<never, never>, Record<never, never>>,
    'Authorize': RouteRecordInfo<'Authorize', '/authorize', Record<never, never>, Record<never, never>>,
    '/authorize/components/Permission': RouteRecordInfo<'/authorize/components/Permission', '/authorize/components/Permission', Record<never, never>, Record<never, never>>,
    '/authorize/components/Role': RouteRecordInfo<'/authorize/components/Role', '/authorize/components/Role', Record<never, never>, Record<never, never>>,
    'Config': RouteRecordInfo<'Config', '/config', Record<never, never>, Record<never, never>>,
    'Dashboard': RouteRecordInfo<'Dashboard', '/', Record<never, never>, Record<never, never>>,
    '/dashboard/components/Ranking': RouteRecordInfo<'/dashboard/components/Ranking', '/dashboard/components/Ranking', Record<never, never>, Record<never, never>>,
    '/dashboard/components/Statistics': RouteRecordInfo<'/dashboard/components/Statistics', '/dashboard/components/Statistics', Record<never, never>, Record<never, never>>,
    '/dashboard/components/VisitorMap': RouteRecordInfo<'/dashboard/components/VisitorMap', '/dashboard/components/VisitorMap', Record<never, never>, Record<never, never>>,
    'FriendlyLink': RouteRecordInfo<'FriendlyLink', '/friendly-link', Record<never, never>, Record<never, never>>,
    'Logging': RouteRecordInfo<'Logging', '/logging', Record<never, never>, Record<never, never>>,
    '/logging/components/System': RouteRecordInfo<'/logging/components/System', '/logging/components/System', Record<never, never>, Record<never, never>>,
    '/logging/components/Visit': RouteRecordInfo<'/logging/components/Visit', '/logging/components/Visit', Record<never, never>, Record<never, never>>,
    'Login': RouteRecordInfo<'Login', '/login', Record<never, never>, Record<never, never>>,
    'Moment': RouteRecordInfo<'Moment', '/moment', Record<never, never>, Record<never, never>>,
    '/moment/components/Aggregation': RouteRecordInfo<'/moment/components/Aggregation', '/moment/components/Aggregation', Record<never, never>, Record<never, never>>,
    '/moment/components/Timeline': RouteRecordInfo<'/moment/components/Timeline', '/moment/components/Timeline', Record<never, never>, Record<never, never>>,
    'OpenSource': RouteRecordInfo<'OpenSource', '/open-source', Record<never, never>, Record<never, never>>,
    'Profile': RouteRecordInfo<'Profile', '/profile', Record<never, never>, Record<never, never>>,
    '/profile/components/Commit': RouteRecordInfo<'/profile/components/Commit', '/profile/components/Commit', Record<never, never>, Record<never, never>>,
    '/profile/components/FunctionGrid': RouteRecordInfo<'/profile/components/FunctionGrid', '/profile/components/FunctionGrid', Record<never, never>, Record<never, never>>,
    'ProfileEdit': RouteRecordInfo<'ProfileEdit', '/profile/edit', Record<never, never>, Record<never, never>>,
    'Setting': RouteRecordInfo<'Setting', '/setting', Record<never, never>, Record<never, never>>,
    'User': RouteRecordInfo<'User', '/user', Record<never, never>, Record<never, never>>,
  }
}
